version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: mareva_front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

  backend:
    build: ./backend
    container_name: mareva_back
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  db:
    image: mysql:latest
    container_name: mareva_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

